compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 7d

npmPreapprovedPackages:
  - beachball
  - p-graph

plugins:
  - checksum: 5ea21341a477907c298afb531f4a0b30f4347e893a3dc9b72c74645a38bb99e760ba8eca5bf1f13cc36d0cdf4ee208df7d96229e54bf604222b3151e5b2b0565
    path: .yarn/plugins/@yarnpkg/plugin-npmrc.cjs
    spec: "https://raw.githubusercontent.com/microsoft/beachball/yarn-plugin-npmrc_v0.5.1/yarn-plugins/npmrc/dist/plugin.js"

yarnPath: .yarn/releases/yarn-4.15.0.cjs
