compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 7d

# Packages that are published via ESRP can be listed here to skip the quarantine.
npmPreapprovedPackages:
  - beachball
  - p-graph

# The npmrc plugin is only enabled with YARN_NPMRC_AUTH_ENABLED in the release pipeline.
plugins:
  - checksum: 5ea21341a477907c298afb531f4a0b30f4347e893a3dc9b72c74645a38bb99e760ba8eca5bf1f13cc36d0cdf4ee208df7d96229e54bf604222b3151e5b2b0565
    path: .yarn/plugins/@yarnpkg/plugin-npmrc.cjs
    spec: "https://raw.githubusercontent.com/microsoft/beachball/yarn-plugin-npmrc_v0.5.1/yarn-plugins/npmrc/dist/plugin.js"

# Using corepack is not currently feasible due to network restrictions in the Azure Pipelines
# release build, since it tries to download yarn from an endpoint `<feed>/registry/@yarnpkg/cli-dist/<version>`
# that appears not to be implemented by Azure DevOps npm feeds.
yarnPath: .yarn/releases/yarn-4.18.0.cjs
