name: Bundle size
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  bundle-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci

      #
      # Steps for PRs
      #

      - name: Measure bundle size
        if: ${{ github.event_name == 'pull_request' }}
        run: npm run bundle-size

      - name: Compare results with "main" branch
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          npx monosize compare-reports --branch main --output markdown --report-files-glob="dist/bundle-size/monosize.json"
          cp node_modules/monosize/dist/monosize.md monosize.md

      - name: Save PR number
        run: echo ${{ github.event.number }} > pr.txt

      - uses: actions/upload-artifact@v3
        if: ${{ github.event_name == 'pull_request' }}
        with:
          name: monosize-report
          if-no-files-found: error
          path: |
            monosize.md
            pr.txt

      #
      # Steps for "main" branch
      #

      - name: Measure bundle size
        if: ${{ github.event_name != 'pull_request' }}
        run: npm run bundle-size

      - name: Upload results
        if: ${{ github.event_name != 'pull_request' }}
        run: npx monosize upload-report --branch main --commit-sha $GITHUB_SHA --report-files-glob="dist/bundle-size/monosize.json"
        env:
          BUNDLESIZE_ACCOUNT_NAME: ${{ secrets.BUNDLESIZE_ACCOUNT_NAME }}
          BUNDLESIZE_ACCOUNT_KEY: ${{ secrets.BUNDLESIZE_ACCOUNT_KEY }}
